version: "3.9"
services:
  mysql:
    image: mysql:5.7.16
    ports:
      - "3306:3306"
    volumes:
      - ./faucet.sql:/data/application/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: faucet
    networks: 
      - app-net

  backend:
    image: backend:1.0.0
    build:
      context: faucet-eth-server
      dockerfile: ./Dockerfile
    networks: 
      - app-net
    ports:
      - "8000:8000" 
    environment:
      DB: mysql
      DB_PORT: 5432 
      PORT: 3011
  frontend:
    image: frontend:1.0.0
    build:
      context: faucet-eth
      dockerfile: ./Dockerfile
    networks: 
      - app-net
    ports:
    - "80:80"
    environment:
      PORT: 8000

networks:
  app-net:
    driver: bridge
    name: app-net
